mlhaus/Open-Source-2023-mon-wed

haikus/andrew.md
=> Andrew's Haiku

haikus/tyler.md
=> Added my haiku message to my markdown file

haikus/anthony.md
=> Anthony's Haiku

haikus/jared.md
=> jared's haiku

haikus/darryl.md
=> Darryl's Haiku

haikus/Miyada.md
=> Miyada Haiku

src/main/java/com/kirkwood/contribution2/Map1.java, src/main/java/com/kirkwood/contribution2/Map2.java
=> Uploaded my map challenges to the files accordingly

src/main/java/com/kirkwood/contribution2/Map1.java, src/main/java/com/kirkwood/contribution2/Map2.java
=> Andrew's Second Contribution

.idea/workspace.xml, src/main/java/com/kirkwood/contribution2/Map1.java, src/main/java/com/kirkwood/contribution2/Map2.java
Please except my pull request.
=> My exercise

src/main/java/com/kirkwood/contribution2/Map1.java, src/main/java/com/kirkwood/contribution2/Map2.java
=> Map1 and Map2

.idea/workspace.xml, src/main/java/com/kirkwood/contribution2/Map1.java, src/main/java/com/kirkwood/contribution2/Map2.java, src/test/java/Map1Test_Chris.java, src/test/java/Map2Test_Chris.java
Added unit tests for Map1.mapAB4_chris testing a several of the coding bat test.
Added unit tests for Map2.allSwap_chris testing all the coding bat tests.
=> Commitment3

.idea/workspace.xml, src/test/java/com/kirkwood/contribution2/Map1Test_Everett.java, src/test/java/com/kirkwood/contribution2/Map2Test_Everett.java
Test classes for both Map1(topping1) and Map2(wordLen) functions
=> Everett tests

.idea/workspace.xml, src/main/java/com/kirkwood/contribution2/Map1.java, src/main/java/com/kirkwood/contribution2/Map1Test_Andrew.java, src/main/java/com/kirkwood/contribution2/Map2Test_Andrew.java
Pull request for Contribution 3. Branch name should have been andrew-map1-test but I misunderstood and only saw after I finished map1. I assume there's a work around to this but I didn't want to break anything.
=> Andrew test

.idea/workspace.xml, src/main/java/com/kirkwood/contribution2/Map1.java, src/main/java/com/kirkwood/contribution2/Map1Test_Andrew.java, src/main/java/com/kirkwood/contribution2/Map2.java, src/main/java/com/kirkwood/contribution2/Map2Test_Andrew.java
=> Andrew map2 test

haiku/gishe.md
I will add additional text as needed.
=> first commit to open source.

.idea/workspace.xml, src/test/java/com/kirkwood/contribution2/Map2Test_Tyler.java
this includes my map 2 for the contributions
=> Tyler map2 tests

src/main/java/com/kirkwood/contribution2/Map1.java, src/main/java/com/kirkwood/contribution2/Map2.java, src/test/java/com/kirkwood/contribution2/Map1_AkoiTest.java, src/test/java/com/kirkwood/contribution2/Map2Test_Akoi.java
My pull request for contribution 3
=> A complete of codebat map1 and test1 (Contribution 3)

.idea/workspace.xml, src/test/java/Map1Test_Kate.java, src/test/java/Map2Test_Kate.java
Added more assertions to each test in my Map1 and Map2 Test Classes.
=> Hacktoberfest Contribution 4

.idea/workspace.xml, src/test/java/com/kirkwood/contribution2/Map1Test_Everett.java, src/test/java/com/kirkwood/contribution2/Map2Test_Everett.java
=> Everett tests 2

.idea/workspace.xml, src/main/java/com/kirkwood/opensource2023monwed/TylerCalculator.java, src/main/webapp/WEB-INF/tyler-calculator.jsp, src/main/webapp/index.jsp, target/Open-Source-2023-mon-wed-1.0-SNAPSHOT/WEB-INF/tyler-calculator.jsp
=> Tyler calculator

src/main/java/com/kirkwood/opensource2023monwed/TylerCalculator.java, src/main/webapp/WEB-INF/tyler-calculator.jsp
=> Tyler updated calculator

src/test/java/com/kirkwood/contribution2/Map1Test.java, src/test/java/com/kirkwood/contribution2/Map2Test.java
=> Map1 Map2 Test.

.idea/workspace.xml, src/main/java/com/kirkwood/KateServlet.java, target/Open-Source-2023-mon-wed-1.0-SNAPSHOT/META-INF/MANIFEST.MF
Updated my compound interest calculator to include the annual interest rate in the output.
I'm not sure why it had me make 2 pull requests for this.
After pulling from upstream, pushing to origin/main kept getting rejected. So, I created a branch off of my previous branch & I hope that solves the issue.
=> Updated My Compound Interest Calculator

.idea/workspace.xml, src/main/java/com/kirkwood/MichaelServlet.java, src/main/webapp/WEB-INF/michael_tvm_calculator.jsp, target/Open-Source-2023-mon-wed-1.0-SNAPSHOT/WEB-INF/michael_tvm_calculator.jsp
Updated the calculator assignment with your requested changes.
=> TVM Calculator Entry

src/test/java/com/kirkwood/contribution2/Map1Test_Wyatt.java
Here is Hacktober fest contribution 3
=> Hacktober fest Contribution 3
